; PlatformIO Project Configuration File
; STM32F401 USB-UART Bridge

[platformio]
src_dir = .
default_envs = genericSTM32F401CB

[env:genericSTM32F401CB]
platform = ststm32
board = genericSTM32F401CB
board_build.mcu = stm32f401cbu6
framework = stm32cube
debug_tool = stlink
upload_protocol = stlink
build_type = release
monitor_speed = 115200
build_flags =
	-DUSE_HAL_DRIVER
	-DSTM32F401xC
	-DHSE_VALUE=25000000
	-g -ggdb
	-DUSB_DEVICE_ONLY
	-I USB_DEVICE/App
	-I USB_DEVICE/Target
	-I Core/Inc
	-I Middlewares/ST/STM32_USB_Device_Library/Core/Inc
	-I Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
build_src_filter =
	+<Core/Src/*.c>
	+<USB_DEVICE/App/*.c>
	+<USB_DEVICE/Target/*.c>
	-<Core/Src/system_stm32f4xx.c>
	-<Core/Src/syscalls.c>
	-<Core/Src/sysmem.c>