; PlatformIO Project Configuration File
; STM32G431 USB-UART Bridge

[platformio]
src_dir = .
default_envs = genericSTM32G431CB

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
board_build.mcu = stm32g431cbu6
framework = stm32cube
debug_tool = stlink
upload_protocol = stlink
build_type = release
monitor_speed = 115200
build_flags =
	-DUSE_HAL_DRIVER
	-DSTM32G431xx
	-DHSE_VALUE=8000000
	-g -ggdb
	-DUSB_DEVICE_ONLY
	-I USB_Device/App
	-I USB_Device/Target
	-I Core/Inc
	-I Middlewares/ST/STM32_USB_Device_Library/Core/Inc
	-I Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
build_src_filter =
	+<Core/Src/*.c>
	+<USB_Device/App/*.c>
	+<USB_Device/Target/*.c>
	-<Core/Src/system_stm32g4xx.c>
	-<Core/Src/syscalls.c>
	-<Core/Src/sysmem.c>